stages:
  # -------------------------------------------
  # Stage 1: Clean raw data
  # -------------------------------------------

  clean:
    cmd: python scripts/run_clean.py --file transactions.csv

    deps:
      - scripts/run_clean.py
      - configs/data.yaml
    outs:
      - data/interim/


  # # -------------------------------------------
  # # Stage 2: Feature Engineering
  # # -------------------------------------------
  features:
    cmd: python scripts/run_features.py --file cleaned_transactions.csv

    deps:
      - scripts/run_features.py
      - configs/features.yaml
      - data/interim/cleaned_transactions.csv
    outs:
      - data/processed/features.parquet

  # # -------------------------------------------
  # # Stage 3: Train model
  # # -------------------------------------------

  train:
    cmd: python scripts/run_training.py --file features_with_target.parquet
    deps:
      - scripts/run_training.py
      - configs/model.yaml
      - data/processed/features_with_target.parquet
    outs:
      - mlruns/
